### ISSUE TITLE
Error thrown when parsing use statements

### ISSUE THREAD

**Issue by ee0pdt** [prettier/plugin-php#1029]
NB: This is my first issue so please let me know if I can improve it in any way for you. 

**@prettier/plugin-php v0.10.2**
[Playground link](https://loilo.github.io/prettier-php-playground/#N4IgDgTgpgLjCWUIHkwIPYDsDOIBcok8mMA6vACYwAW+AHAAwA0IMAhgEblW14BMLAK7YoAFU648AMzYAbES2zEA5rKgBFQehhR8M+VBYwIbeLJUBhdAFtrbfCExZdLDiYDGUAMowAnmocwbAgAWj4QFmgAR0F4aAAFE2U7PTkFEGIRCBhEtmT7aTSoAF8WKAp4GHQUNHgsSVA2bBhUg1KMzDBBFrwQAB4AfjBqMAAdTEw2ayhsMDZPAAIrEgh0WTUIbFHRgEF4gEkAbnHx4SgF7Ys2CA4sS+vbzCYL3bAwZ+2AJRmwesMX-adbofXbdagggCqnwAMsdMCBikA)

**Input:**
```php
<?php
namespace Controllers\API;

use \Carbon\Carbon, \App, \Response, \Input, \Auth, \URL;

```

**Output:**
```php
Parse Error : syntax error, unexpected '\' (T_NS_SEPARATOR), expecting ';' on line 4

  2 | namespace Controllers\API;
  3 | 
> 4 | use \Carbon\Carbon, \App, \Response, \Input, \Auth, \URL;
    |                          ^
  5 | 
```

I'm not sure the backslashes are required but I think the parser shouldn't fail on them as this is valid code and runs

**Comment by Loilo** [comment]
Great catch, thanks for reporting. 👍 

I've dug into this a little and it turns out to be a problem with the PHP parser we use (which is not developed by us). I've created [an issue](https://github.com/glayzzle/php-parser/issues/291) over there as well as [a PR](https://github.com/glayzzle/php-parser/issues/292) to fix it.

Now we need to wait for
* the PR to get reviewed and merged
* a new version of the parser to get published

and we're good to go.

This may or may not take a while, so please be patient. 🙂
