### ISSUE TITLE
Skip standalone tests during development

### ISSUE THREAD

**Issue by czosel** [prettier/plugin-php#1276]
It would be nice if we could skip everything related to standalone tests during development, for two reasons:
* they always seem to pass when the node-based tests are passing
* faster turnaround times when running a single test / few tests

Currently it's already possible to skip the standalone tests using the env setting `SKIP_STANDALONE_TESTS=true`, but I'd like to skip the creation of the rollup bundle altogether.

@loilo Do you agree this is a good idea? If yes, would it be hard to implement?

**Comment by loilo** [comment]
I agree. The test itself is not the problem, but the standalone build before each and every test is annoying as heck. 😅

This should generally be straightforward to implement, but there is a decision to be made how we want it to work (more on that in a second).

We're currently skipping the standalone test if a [`SKIP_STANDALONE_TESTS` environment variable] is set to `true`(https://github.com/prettier/plugin-php/blob/master/jest.config.js#L23), but we don't seem to use that variable anywhere.

We could remove the standalone build from the `pretest` script and swap around the check so the according tests are only executed when an environment variable (for example `STANDALONE_TESTS`) is set.

However, this would bring the burden on us to decide when this environment variable would actually be used (because if we don't enforce it to be used, we'll basically never again test the standalone build).

So the decision has to be made when that environment variable would be set. I see the following ways:

1. We could include a full test run (including building & testing standalone) in our `prepublishOnly` script.

   ✅ This would ensure that all features are tested.
   ❌ The wait time before publishing would become annoyingly long, especially because we naturally already manually invoke a full test run without standalone before we publish anything.

2. We could modify the environment variable check in such a way that, when the variable is set, *only* standalone tests would be run. We could then include a standalone-only test run in the `prepublishOnly` script.

   ✅ It would be made sure that the standalone build is tested some time.
   ✅ Prepublish script execution time would be kept at a bearable level.
   ❌ Running tests in a `prepublishOnly` script but then testing only the arguably *least important part* of the library sounds incredibly stupid.

3. > I liked the following approach most at first but then realized it's completely useless. I'll still keep it here for public entertainment.

   A very clean solution would be to use [dotenv](https://www.npmjs.com/package/dotenv). One could permanently disable standalone tests in their own environment in a clear and obvious way.

   ✅ It's clean.
   ❌ It's stupid. Because you would not be forced to run standalone tests in any way, it's just as good as not having a well-defined way to run standalone tests *at all*.

4. Just an idea that came to my mind, but I have no idea whether this is even doable with a reasonable amount of effort:

   We could entirely delegate publishing versions to the CI (i.e. to GitHub Actions). The CI would run the tests (*all* tests, including standalone) and publish a new version if they pass.

   ✅ It would completely take the responsibility of remembering to run standalone tests out of our brains and hand it to a machine. This is a good thing.
   ❌ I have no experience with GitHub Actions. I would not know how to implement this, neither do I know if it's even *possible* to create a GitHub action that has a manual trigger.

Pick your poison. 😁

(Or tell me that you've got a much more straightforward idea. I tend to think a little but to much outside the box with those things. 🙃)

**Comment by czosel** [comment]
Wow, thanks for the extensive feedback! :100: 

I actually don't really care if publishing takes a little longer than strictly necessary. Currently, the bundle is built on _every single test run_, so building and testing the bundle only on publish seems like a huge improvement (and the full test suite takes just 19 seconds to run on my laptop).

Looking in the future, what you suggested in (4) sounds really good. But I guess development and release frequency would have to intensify quite a bit until this is really worth it :wink: 

> I liked the following approach most at first but then realized it's completely useless. I'll still keep it here for public entertainment.

:laughing: 
I also really like `dotenv`, but agree that it's not really solving our problem.

Do you want to give (1) a shot?

**Comment by loilo** [comment]
Sure.

(And that's what I meant by out-of-the-box thinking. I realized that (1) is annoying, but I did not consider that it literally does not matter with our current release frequency.)

"Overengineering" is my middle name. 😂
