### ISSUE TITLE
do not add blank before my <?php header

### ISSUE THREAD

**Issue by dvaknheo** [prettier/plugin-php#1302]
**Prettier 1.16.4**

**PHP Plugin 0.10.2**

**Input:**

```php
<table>
<?php 
foreach($recordset as $line){
?>
    <tr>
<?php
    foreach($line as $v){
?>
        <td><?=$v?><td>
<?php
    }
?>
    </tr>
<?php
}
?>
</table>
```

**Output:**

```php
<table>
	<?php 
foreach($recordset as $line){
?>
	<tr>
		<?php
    foreach($line as $v){
?>
		<td>
			<?=$v?>
			<td>
				<?php
    }
?>
	</tr>
	<?php
}
?>
</table>
```

**Expected behavior:**

I want to keep the output as the same to input

is any option to keep my php code output ?

**Comment by czosel** [comment]
Hi @dvaknheo,
Which version of the plugin are you using? I wasn't able to reproduce the issue with the latest release, please see [here](https://loilo.github.io/prettier-php-playground/#N4IgDgTgpgLjCWUIHkwIPYDsDOIBcok8mMA6vACYwAW+AHAAwA0IMAhgEblW14AsLAK7YoAFU648AMzYAbES2zEA5rKgBFQehhR8M+VBYwIbeLJUBhdAFtrbAAoAJe-hCYsulhxMBjKAGUYAE81VzBsCABaACYQFmgAR0F4aHsTZTs9OQUQYhEIGDS2DLYsgwBfFigKeBh0FDR4LElQNmwYMpFK3MwwQQ68EAAedg41AD4AHUwhgH4wajAAAmmpeqg2H2oACgASaB96ihEYJbal3fNMKABKYGnZqcwll6WRiCe5hbBp16W16CbHaXYhQM7YC4ANzuDyefz+Iwo4zmAF5dpDHkMAPQwJHTL6LX6vcqwokvbHGT7zQmYEmYR74nGcCYgcpAA). Also note that you're missing the slash in the closing table cell (`<td>` instead of `</td>`) - this doesn't seem to affect the formatted output though.

**Comment by dvaknheo** [comment]
oh , seem that I use another format in  vs code ,  but not the prettier (thougt i don't know how to install prettier/php
I got an mistake.

and
--require-pragma 

is fit to me.
thank.

may close issue.

**Comment by czosel** [comment]
Glad I could help :blush:
