### ISSUE TITLE
Option to keep "else if" from converting into "elseif"

### ISSUE THREAD

**Issue by kianbomba** [prettier/plugin-php#1457]
Is there any such of option in `.prettierc` to prevent prettier converting `else if` into `elseif` ? 
If not, would it be worth to have the option to stop the converting ?

**Comment by evilebottnawi** [comment]
What is the problem?

**Comment by kianbomba** [comment]
So I prefer to have `else if` over `elseif` in php, but when i run the prettier, it just convert `else if` into `elseif`. And i have not figured out if there is an option to stop prettier to do that.

**Comment by evilebottnawi** [comment]
This is the philosophy of the prettier, no options for preferable styles

**Comment by kianbomba** [comment]
alrighty, so you r saying that the plugin does not have option to support preferable styles ? do you think there should be one for this ? if not then im happy to close the issue then

**Comment by evilebottnawi** [comment]
No options, we really don't need it :smile:

**Comment by darovic** [comment]
> This is the philosophy of the prettier, no options for preferable styles

This really isn't true. Prettier allows the user to configure options based on their style, and adapts the code style to the user-defined style. Otherwise, there would be no options at all. `{` on the same line as a function or class declaration or on the line after it is a brilliant example, and you support this.
