### ISSUE TITLE
Automatically add trailing semicolons just like prettier does for javascript

### ISSUE THREAD

**Issue by danneu** [prettier/plugin-php#1485]
**@prettier/plugin-php v0.14.2**
[Playground link](https://loilo.github.io/prettier-php-playground/#N4IgDgTgpgLjCWUIHkwIPYDsDOIBcok8mMA6vACYwAW+AHAAwA0IMAhgEblW14AsLAK7YoAFU648AMzYAbES2zEA5rKgBFQehhR8M+VBZhqYAGpIlWfCACsAOj4gWMCG3iyVAYXQBbH2wAFAAkA-BdBQxAOVwBjKABlGABPNWswbAgAWgAmJxBoAEdBeGgA12V-PTkFEGIRCBgytgq2KoMAXxYoCngYdBQ0eCxJUDZsGDaRTtrMMEEJvBAAHgB+YzAAHUwtqUFMGIxMAAIIPYAKABI2AEoj4C2jx6eoGOp0S5ujgHovpczMo4ASSOynQRw4bBiAGsjn0jmwKBRYdR4NgTlA5EcivBofDMEjIFBsGjsGwAG5QB5PR7QGCCCDHPjZADcW3aWxA7SAA)

**Input:**
```php
<?php

function run($a) {
      echo($a) //<-- I go back to add this real quick and press save
      return 42;
}

```

**Output:**
```php
Parse Error : syntax error, unexpected 'return' (T_RETURN), expecting ';' on line 5

  3 | function run($a) {
  4 |       echo($a) //<-- I go back to add this real quick and press save
> 5 |       return 42;
    |      ^
  6 | }
  7 | 
```

One of the greatest features of Prettier is that it saves me from manual labor. Prettier is so good with Javascript that I won't even bother indenting nor applying semicolons while I write rapid code because I know Prettier will do the RSI chore for me.

That Prettier indeed does it for Javascript is what makes this slightly more interesting than the typical wishlist bikeshedding. 

I also think a very simple though nonexhaustive heuristic would be sufficient for 90% of cases: add a semi if the next line is indented to the same spot and we aren't inside a comma-delimited context.

**Comment by czosel** [comment]
I'm afraid this won't be possible. Prettier works like this:

1. Convert source code into an abstract syntax tree (AST) using a parser
2. Convert the AST into another data structure ("doc") that contains information about how to print the source code
3. Convert the "doc" into formatted source code

For step 1 to succeed, the input needs to be a syntactically valid program. That's why prettier also fails when you, for example, forgot some closing curly brace in your program.

For JS, semicolons are optional, so the parser can handle code without semicolons. For PHP, that's not the case. One would have to implement a special PHP parser that doesn't require semicolons to be present, which I assume would be quite difficult.

**Comment by danneu** [comment]
That makes sense, the parser already has to implement ASI knowledge, so it's trivial to then add the semicolon glyph or not when emitting the output. Seems obvious now, thanks for explaining. Then could we get this feature behind a `--danneu` flag? Just playing, cheers.
