### ISSUE TITLE
Repeated long functions are splitted into several lines

### ISSUE THREAD

**Issue by pierresh** [prettier/plugin-php#1647]
**Prettier 2.2.1**

**PHP Plugin 0.16.1**

**Input:**

```php
<?php

$query->bindParam(':order_code', $order_code, PDO::PARAM_STR);
$query->bindParam(':order_name', $data['order_name'], PDO::PARAM_STR);
$query->bindParam(':order_vendor_id', $data['order_vendor_id'], PDO::PARAM_INT);
$query->bindParam(':order_status', $data['order_status'], PDO::PARAM_STR);
$query->bindParam(':order_issue_date', $data['order_issue_date'], PDO::PARAM_STR);
$query->bindParam(':order_delivery_date', $data['order_delivery_date'], PDO::PARAM_STR);
$query->bindParam(':order_arrival_date', $data['order_arrival_date'], PDO::PARAM_STR);
$query->bindParam(':order_tracking', $data['order_tracking'], PDO::PARAM_STR);
$query->bindParam(':order_invoice_date', $data['order_invoice_date'], PDO::PARAM_STR);
$query->bindParam(':order_payment_date', $data['order_payment_date'], PDO::PARAM_STR);
$query->bindParam(':order_ship_information', $data['order_ship_information'], PDO::PARAM_STR);


```

**Output:**

```php
<?php

$query->bindParam(":order_code", $order_code, PDO::PARAM_STR);
$query->bindParam(":order_name", $data["order_name"], PDO::PARAM_STR);
$query->bindParam(":order_vendor_id", $data["order_vendor_id"], PDO::PARAM_INT);
$query->bindParam(":order_status", $data["order_status"], PDO::PARAM_STR);
$query->bindParam(
    ":order_issue_date",
    $data["order_issue_date"],
    PDO::PARAM_STR
);
$query->bindParam(
    ":order_delivery_date",
    $data["order_delivery_date"],
    PDO::PARAM_STR
);
$query->bindParam(
    ":order_arrival_date",
    $data["order_arrival_date"],
    PDO::PARAM_STR
);
$query->bindParam(":order_tracking", $data["order_tracking"], PDO::PARAM_STR);
$query->bindParam(
    ":order_invoice_date",
    $data["order_invoice_date"],
    PDO::PARAM_STR
);
$query->bindParam(
    ":order_payment_date",
    $data["order_payment_date"],
    PDO::PARAM_STR
);
$query->bindParam(
    ":order_ship_information",
    $data["order_ship_information"],
    PDO::PARAM_STR
);


```

**Expected behavior:**
I think that these lines should not be broken down. I know that they might be longer than 80 characters but as they are repeated, they are much more readable like this rather than splitted on 5 different lines.
I have found that `// prettier-ignore-start` and `// prettier-ignore-end` are not supported but that might be a solution to such problems.

```
<?php

$query->bindParam(':order_code', $order_code, PDO::PARAM_STR);
$query->bindParam(':order_name', $data['order_name'], PDO::PARAM_STR);
$query->bindParam(':order_vendor_id', $data['order_vendor_id'], PDO::PARAM_INT);
$query->bindParam(':order_status', $data['order_status'], PDO::PARAM_STR);
$query->bindParam(':order_issue_date', $data['order_issue_date'], PDO::PARAM_STR);
$query->bindParam(':order_delivery_date', $data['order_delivery_date'], PDO::PARAM_STR);
$query->bindParam(':order_arrival_date', $data['order_arrival_date'], PDO::PARAM_STR);
$query->bindParam(':order_tracking', $data['order_tracking'], PDO::PARAM_STR);

```

Thanks, besides this point, Prettier is really awesome :)

**Comment by czosel** [comment]
Hi @pierresh!
A cheap workaround for the lack of of support for `prettier-ignore-{start/end}` might be to wrap the code block in braces: [see playground](https://loilo.github.io/prettier-php-playground/#N4IgDgTgpgLjCWUIHkwIPYDsDOIBcok8mMA6vACYwAW+AHAAwA0IMAhgEblW14AsLAK7YoAFU648AMzYAbES2zEA5rKgBFQehhR8M+VBZhqYAGpIlWfCACsAOj4gWMCG3iyVAYXQBbH2wAFAAkA-BdBQxAOVwBjKABlGABPNWswbAgAWgAmJxBoAEdBeGgA12V-PTkFEGIRCBgytgq2KoMAXxYoCngYdBQ0eCxJUDZsGDaRTtrMMEEJvBAAHgB+YzAAHUwtgHodgAJIWAQkTPhlTH6oLeAtgBIipCTMgD4OYgoAtlcfAAoAcjw-QoSAA+jF0CD-kx9ndgWCISCYQEACLIPB4AIAQQASliALKg+KiHEASgA3PdHhBnm8Pl8fgCgRAQRBQZg2D4oNDYRQ2OwANr-eFsjlc-4AXWRaIx2LxhOJZMpmAeERpr3emE+305TJFoIAblAtf1QZQeXc+YLhSywUaTWzzVL9qj0ZjcQTQQBJAByogpVLVtM12sZgP1435wgtVrYQoj7Bg0edrtlHoVJIDKupwfpOr+4dtjuw2AioKt3Jhlv5cZtrLNJbLFcl0rdcs9iqzqqeGrzYeZ9ZBHiNNPL-MrvJr8aL5agw6eY50LZdMvd8qJmeV3fVdK1DN1hfr3wg8ANckXE+r1v1x9P5+bKdX7YzSsDPd3oYPA7BLjYMQA1ioMZTnWP6xIBmDKMuqZrh2m5vjuIb7gW36OpgBroPAcQXsB14zsQGFYVAOGPm26Ybq+2ZBr2e75nqM5gGwSRciQOFVrG071oxzHGjAJGtmm66dluOY0Z+KERtQ8BgGamBSP0-gYJguG1pJ0myfJECKUMymkYJcGUe0IDtEAA). Otherwise, I'm afraid this won't be something we can act on.

**Comment by pierresh** [comment]
Thanks a lot for your prompt reply, this workaround is totally acceptable :)
