### ISSUE TITLE
the default value of `tabWidth` differs from the setting in Prettier itself

### ISSUE THREAD

**Issue by oekazuma** [prettier/plugin-php#1999]
As far as I can tell from the Prettier documentation, the default value for `tabWidth` is currently `2`.
https://prettier.io/docs/en/options.html#tab-width

However, this plugin overwrites the default value to `4`, even though the README says `Same as in Prettier`.

This is confusing and I would like to see it fixed.

**Comment by czosel** [comment]
With "same as in Prettier" we meant that the configuration option has the same meaning as in Prettier. We went for `4` instead of `2` because that's standard in the PHP community, specifically in PSR-2 (see https://www.php-fig.org/psr/psr-2/). I don't think we'll change the default, but I'm open to point out the difference more clearly in the README.

**Comment by oekazuma** [comment]
Thanks for letting me know.

I must confess that I am not familiar with the PHP community and did not know about PSR-2.
I will close the currently submitted PR and submit a PR to add to the README why the default for tabWidth is 4.

**Comment by czosel** [comment]
No worries, and thanks for the PR! :+1:
