### ISSUE TITLE
some inline comments still being moved to next line

### ISSUE THREAD

**Issue by roippi** [prettier/plugin-php#428]
Moved from https://github.com/prettier/plugin-php/issues/191#issuecomment-398600922 into new issue

Just ran into this with 0.2.1:

```php
//input
$foo['options'] = array_slice($foo['options'], 0, \Forbidden\Classes\Secret_Class::$amount); // @codingStandardsIgnoreLine because I like to sweep problems under the rug
```

```php
//output
$foo['options'] = array_slice(
  $foo['options'],
  0,
  \Forbidden\Classes\Secret_Class::$amount
); // @codingStandardsIgnoreLine because I like to sweep problems under the rug
```

**Comment by mgrip** [comment]
Unfortunately I'm not sure we're going to be able to do anything about this. Since its all on one line, we don't know what node the comment should be associated to. JS does the same thing

https://prettier.io/playground/#N4Igxg9gdgLgprEAuEASAZhCBtA5BABxgEtoBnXAXQAIBeagQwCcmGBPAfTIBtiw4AFBix5CJclQA01AAzSAYhCYAjYgBM1CAMLcGZMnDIBlOGCZwYHHXrJIkqBgFsIAV1gBKANzUA9D+qGvLAAtGrEZAzK3HDBQXDUUBDBLgbBynCY5qEZxFBwADpQIJIgYqRQZMigzEwQAO4ACswIlSgMAG4Q6sUgyqxgANYWRgQMYLkA5sgwTC5wJbkGTDANrBOODMjoDNwGJQBWZAAeAEL9QzBGTnAAMrlwWzt7IKNMS8i9kWzc0D0ETLkYAB1dQwAAWyAAHHIXrUDEDWAQPv9DHAmO0HiVzABHFzEcyrBjrTZIba7eYgAyOYjTWYUsiTaIARRcEHgj3JJRgkRBanByAATFzWMQghMtBBHBsPok8j0UnAACqRVpkgwAX3VQA

Relevant discussion: https://github.com/prettier/prettier/issues/1267
