### ISSUE TITLE
How to format HTML in PHP templates

### ISSUE THREAD

**Issue by claytonrcarter** [prettier/plugin-php#845]
**Prettier 1.15.2**  
**PHP Plugin 0.9.0**

Now that prettier supports formatting HTML, how can we have plugin-php format PHP and HTML in a PHP file?

**Input:**
```
<?php
$somePoorly    = 'formatted'. 'code' .
'right'       .
 ( isset( $nope) ? 'here'
:
'and here'
)
;

?>
<html
><head

>

</head>
<body>
More
bad
code here.
</body
>

</html>
```

**Output of `prettier test.php`:** (PHP is properly formatted, HTML is not.)

```php
<?php
$somePoorly =
    'formatted' . 'code' . 'right' . (isset($nope) ? 'here' : 'and here'); ?>
<html
><head

>

</head>
<body>
More
bad
code here.
</body
>

</html>
```

**Output of `prettier test.php --parser html`:** (HTML is properly formatted, PHP is not.)

```php
<?php $somePoorly = 'formatted'. 'code' . 'right' . ( isset( $nope) ? 'here' :
'and here' ) ; ?>
<html>
  <head> </head>
  <body>
    More bad code here.
  </body>
</html>
```

**Expected behavior:** (Both PHP & HTML are properly formatted.)

```php
<?php
$somePoorly =
    'formatted' . 'code' . 'right' . (isset($nope) ? 'here' : 'and here'); ?>
<html>
  <head> </head>
  <body>
    More bad code here.
  </body>
</html>
```

**Comment by evilebottnawi** [comment]
It is unsafe, we can't format code like this: `<<?php echo 'img; ?> src="http://example.com/image.png" <?php echo attributes(); ?>>`

**Comment by evilebottnawi** [comment]
So i don't think it is good idea enable this, also we have a lot of problem in `inline` nodes and their formatting

**Comment by adamroyle** [comment]
@claytonrcarter Vue templates can be parsed by the html parser because they are html-compliant. 

PHP can't be parsed by the html parser because php is not html-compliant.

And html can't be parsed by php parser since it's not valid php.

Using a combination of parsers (php for php blocks and html for text nodes) is impossible for the majority of cases where php is intermingled with html like evilebottnawi's example because the text node is not valid html on its own, it requires the output from php to be valid.

Another reason is text nodes might not actually be html, it could literally be any type of arbitrary text.

**Comment by claytonrcarter** [comment]
Fair enough. This all makes complete sense and I'm realizing that this is probably the wrong place for this issue anyway. I found this issue on the main Prettier repo with some context on HTML templates: https://github.com/prettier/prettier/issues/5428
